---
galaxy_info:
  author: Dan Nixon
  description: Performs bare minimum system configuration
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: ArchLinux
    - name: Debian
    - name: Ubuntu

dependencies: []
